# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', otree.db.models.IntegerField(null=True)),
                ('created_at', otree.db.models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', otree.db.models.DateTimeField(auto_now=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_statements', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', otree.db.models.IntegerField(null=True)),
                ('created_at', otree.db.models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', otree.db.models.DateTimeField(auto_now=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_statements', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', otree.db.models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', otree.db.models.DateTimeField(auto_now=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', otree.db.models.CurrencyField(null=True)),
                ('value', otree.db.models.CurrencyField(null=True)),
                ('ask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='double_auction.Ask')),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='double_auction.Bid')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('active', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='double_auction_group', to='otree.Session')),
            ],
            options={
                'db_table': 'double_auction_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', otree.db.models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', otree.db.models.DateTimeField(auto_now=True, null=True)),
                ('quantity', otree.db.models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('active', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('endowment', otree.db.models.CurrencyField(default=0, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='double_auction.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='double_auction_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='double_auction_player', to='otree.Session')),
            ],
            options={
                'db_table': 'double_auction_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', otree.db.models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', otree.db.models.DateTimeField(auto_now=True, null=True)),
                ('cost', otree.db.models.FloatField(null=True)),
                ('value', otree.db.models.FloatField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='double_auction.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('num_sellers', otree.db.models.IntegerField(null=True)),
                ('num_buyers', otree.db.models.IntegerField(null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='double_auction_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'double_auction_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='double_auction.Subsession'),
        ),
        migrations.AddField(
            model_name='item',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='double_auction.Slot'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='double_auction.Subsession'),
        ),
        migrations.AddField(
            model_name='contract',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='double_auction.Item'),
        ),
        migrations.AddField(
            model_name='bid',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='double_auction.Player'),
        ),
        migrations.AddField(
            model_name='ask',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to='double_auction.Player'),
        ),
    ]
